export const products = [
  {
    _id: '1',
    name: 'Muscle Fit Band-collar Shirt',
    price: 24.99,
    image: '/images/Home_Muscle_Fit_white.jfif',
    images: ['/images/Muscle_Fit_white.jfif', '/images/Muscle_Fit_black.jfif'],
    color: ['white', 'black'],
    description: `Shirt in cotton poplin with stretch. Band collar, classic button placket,
       and yoke at back with darts. Long sleeves and cuffs with adjustable buttoning, sleeve placket,
       and link button. Rounded hem. Muscle Fit - designed to showcase physique. Narrow shoulders and tapered sleeves 
       for a flattering silhouette.`,
    sizes: [
      { name: 'XXS', inStock: false },
      { name: 'XS', inStock: true },
      { name: 'S', inStock: true },
      { name: 'M', inStock: true },
      { name: 'L', inStock: true },
      { name: 'XL', inStock: true },
      { name: '2XL', inStock: true },
      { name: '3XL', inStock: true },
    ],
  },
  {
    _id: '2',
    name: 'Twill Overshirt',
    price: 34.99,
    image: '/images/hometwill_overshirt.jfif',
    images: [
      '/images/twill_Overshirt_brown.jfif',
      '/images/Twill_overshirt_green.jfif',
    ],
    color: ['brown', 'green'],
    description: `Overshirt in twill with a collar, buttons at front, and yoke at back. 
      Chest pockets with flap and button. Long sleeves with buttons at cuffs.`,
    sizes: [
      { name: 'XXS', inStock: false },
      { name: 'XS', inStock: true },
      { name: 'S', inStock: true },
      { name: 'M', inStock: true },
      { name: 'L', inStock: true },
      { name: 'XL', inStock: true },
      { name: '2XL', inStock: true },
      { name: '3XL', inStock: true },
    ],
  },
  {
    _id: '3',
    name: 'Relaxed Fit Oxford Shirt',
    price: 24.99,
    image: '/images/Relaxed_Shirt_home.jfif',
    images: ['/images/Relaxed_Shirt_1.jfif', '/images/Relaxed_Shirt_2.jfif'],
    color: ['lightblue', 'darkgray'],
    description: `We believe that greater transparency will help lead the change towards a more sustainable future. 
      As a step in this long-term commitment, 
      we’re sharing how and where our products are made wherever possible.`,
    sizes: [
      { name: 'XXS', inStock: false },
      { name: 'XS', inStock: true },
      { name: 'S', inStock: true },
      { name: 'M', inStock: true },
      { name: 'L', inStock: true },
      { name: 'XL', inStock: true },
      { name: '2XL', inStock: true },
      { name: '3XL', inStock: true },
    ],
  },
  {
    _id: '4',
    name: 'Relaxed Fit Corduroy Overshirt',
    price: 49.99,
    image: '/images/Relaxed_overshirt_home.jfif',
    images: [
      '/images/Relaxed_overshirt_1.jfif',
      '/images/Relaxed_overshirt_2.jfif',
    ],
    color: ['black', 'Moccasin'],
    description: `Padded overshirt in soft corduroy. Collar, snap fasteners at front, long sleeves, and cuffs with sleeve placket snap fastener. Chest pockets with flap and snap fastener, diagonal welt front pockets, and slit at sides of hem. Quilted lining. 
      Relaxed Fit – a straight fit with good room for movement for a comfortable, relaxed silhouette.`,
    sizes: [
      { name: 'XXS', inStock: false },
      { name: 'XS', inStock: true },
      { name: 'S', inStock: true },
      { name: 'M', inStock: true },
      { name: 'L', inStock: true },
      { name: 'XL', inStock: true },
      { name: '2XL', inStock: true },
      { name: '3XL', inStock: true },
    ],
  },
  {
    _id: '5',
    name: 'Relaxed-fit Hoodie',
    price: 19.99,
    image: '/images/Hoodie_home.jfif',
    images: ['/images/Relaxed_hoodie_1.jfif', '/images/Relaxed_hoodie_2.jfif'],
    color: ['LightGreen', 'DodgerBlue'],
    description: ` The Hoodie. Relaxed-fit sweatshirt hoodie in cotton-blend
       fabric with soft, brushed inside. Jersey-lined drawstring hood,
       kangaroo pocket, and long sleeves. Wide ribbing at cuffs and hem.`,
    sizes: [
      { name: 'XXS', inStock: false },
      { name: 'XS', inStock: true },
      { name: 'S', inStock: true },
      { name: 'M', inStock: true },
      { name: 'L', inStock: true },
      { name: 'XL', inStock: true },
      { name: '2XL', inStock: true },
      { name: '3XL', inStock: true },
    ],
  },
  {
    _id: '6',
    name: 'Relaxed Fit Sweatshirt',
    price: 12.99,
    image: '/images/Relaxed_Sweatshirt_home.jfif',
    images: [
      '/images/Relaxed_Sweatshirt_1.jfif',
      '/images/Relaxed_Sweatshirt_2.jfif',
    ],
    color: ['lightgray', 'black'],
    description: ` The Sweatshirt. Relaxed-fit sweatshirt in cotton-blend fabric with soft,
       brushed inside. Dropped shoulders and ribbing at neck, cuffs, and hem.`,
    sizes: [
      { name: 'XXS', inStock: false },
      { name: 'XS', inStock: true },
      { name: 'S', inStock: true },
      { name: 'M', inStock: true },
      { name: 'L', inStock: true },
      { name: 'XL', inStock: true },
      { name: '2XL', inStock: true },
      { name: '3XL', inStock: true },
    ],
  },
  {
    _id: '7',
    name: 'Long-sleeved Jersey Top',
    price: 24.99,
    image: '/images/Long-sleeved_home.jfif',
    images: ['/images/Long-sleeved_1.jfif', '/images/Long-sleeved_2.jfif'],
    color: ['dark', 'gray'],
    description: `Oversized top in cotton jersey.
       Crew neck, dropped shoulders, and long sleeves. Ribbing at neckline and cuffs.`,
    sizes: [
      { name: 'XXS', inStock: false },
      { name: 'XS', inStock: true },
      { name: 'S', inStock: true },
      { name: 'M', inStock: true },
      { name: 'L', inStock: true },
      { name: 'XL', inStock: true },
      { name: '2XL', inStock: true },
      { name: '3XL', inStock: true },
    ],
  },
  {
    _id: '8',
    name: 'Oversized Graphic T-shirt',
    price: 17.99,
    image: '/images/Oversized_shirt_1.jfif',
    images: [
      '/images/Oversized_shirt_home.jfif',
      '/images/Oversized_shirt_2.jfif',
    ],
    color: ['black', 'gray'],
    description: `Oversized T-shirt in soft, organic cotton jersey with a printed graphic design at front.
       Ribbed crew neck and dropped shoulders.`,
    sizes: [
      { name: 'XXS', inStock: false },
      { name: 'XS', inStock: true },
      { name: 'S', inStock: true },
      { name: 'M', inStock: true },
      { name: 'L', inStock: true },
      { name: 'XL', inStock: true },
      { name: '2XL', inStock: true },
      { name: '3XL', inStock: true },
    ],
  },
];
